export type Room={id:string;name:string;floor:number;x:number;y:number;w:number;h:number;area:number};
export type BuildingModel={modelId:string;version:number;status:"draft"|"unresolved";units:"m";plot:{width:number;depth:number};rooms:Room[]};
export const MODEL_KEY="build-ai:building-model:v3";
export const DEFAULT_PLOT={width:12,depth:10};
function storageKey(projectId?:string){return projectId?`build-ai:building-model:${projectId}:v1`:MODEL_KEY;}
export function roomArea(w:number,h:number){return Math.round(w*h*100)/100;}
export function normalizeRoom(r:Room,plot=DEFAULT_PLOT):Room{const w=Math.min(plot.width,Math.max(.5,Number.isFinite(r.w)?r.w:.5));const h=Math.min(plot.depth,Math.max(.5,Number.isFinite(r.h)?r.h:.5));const x=Math.max(0,Math.min(plot.width-w,Number.isFinite(r.x)?r.x:0));const y=Math.max(0,Math.min(plot.depth-h,Number.isFinite(r.y)?r.y:0));return {...r,w,h,x,y,area:roomArea(w,h)};}
export function createModel(rooms:Room[],version=1,projectId?:string,plot=DEFAULT_PLOT):BuildingModel{return{modelId:projectId?`bm-${projectId}-v1`:"bm-local-v3",version,status:"unresolved",units:"m",plot:{width:Math.max(.5,plot.width),depth:Math.max(.5,plot.depth)},rooms:rooms.map(r=>normalizeRoom(r,plot))};}
export function applyModelChange(model:BuildingModel,id:string,patch:Partial<Pick<Room,"x"|"y"|"w"|"h">>):BuildingModel{const rooms=model.rooms.map(r=>r.id===id?normalizeRoom({...r,...patch},model.plot):r);return{...model,version:model.version+1,rooms};}
function overlaps(a:Room,b:Room){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
export function overlapPairs(rooms:Room[]){const pairs:[string,string][]=[];for(let i=0;i<rooms.length;i++)for(let j=i+1;j<rooms.length;j++){const a=rooms[i],b=rooms[j];if(a.floor===b.floor&&overlaps(a,b))pairs.push([a.id,b.id]);}return pairs;}
export function boundaryViolations(model:BuildingModel){return model.rooms.filter(r=>r.x<0||r.y<0||r.w<=0||r.h<=0||r.x+r.w>model.plot.width||r.y+r.h>model.plot.depth).map(r=>r.id);}
export function validateModel(model:BuildingModel){const boundary=boundaryViolations(model);const overlaps=overlapPairs(model.rooms);return{overlap:overlaps.length>0,boundary,overlaps,valid:overlaps.length===0&&boundary.length===0};}
function validModel(value:unknown):value is BuildingModel{if(!value||typeof value!=="object")return false;const m=value as BuildingModel;return typeof m.modelId==="string"&&Number.isInteger(m.version)&&m.version>=1&&m.units==="m"&&Number.isFinite(m.plot?.width)&&m.plot.width>0&&Number.isFinite(m.plot?.depth)&&m.plot.depth>0&&Array.isArray(m.rooms);}
export function loadModel(projectId:string|undefined,fallback:BuildingModel){try{const raw=localStorage.getItem(storageKey(projectId));if(!raw)return fallback;const parsed=JSON.parse(raw);if(validModel(parsed))return{...parsed,modelId:projectId?`bm-${projectId}-v1`:parsed.modelId,rooms:parsed.rooms.map(r=>normalizeRoom(r,parsed.plot))};}catch{}return fallback;}
let saveTimer:ReturnType<typeof setTimeout>|undefined;
let saveSequence=0;
let pendingProject:string|undefined;
let pendingModel:BuildingModel|undefined;
export function saveModel(projectId:string|undefined,model:BuildingModel){const normalized={...model,rooms:model.rooms.map(r=>normalizeRoom(r,model.plot))};try{localStorage.setItem(storageKey(projectId),JSON.stringify(normalized));}catch{}if(!projectId)return;pendingProject=projectId;pendingModel=normalized;const sequence=++saveSequence;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(sequence===saveSequence&&pendingProject===projectId&&pendingModel===normalized)void persistModel(projectId,normalized);},500);}
function notifyModelConflict(projectId:string,currentVersion:number){if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("build-ai:model-conflict",{detail:{projectId,currentVersion}}));}
async function persistModel(projectId:string,model:BuildingModel){try{const expectedVersion=Math.max(0,model.version-1);const response=await fetch(`/api/projects/${encodeURIComponent(projectId)}/model`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({expectedVersion,status:model.status,model})});if(response.ok){pendingModel=undefined;return;}if(response.status===409){const payload=await response.json().catch(()=>null);notifyModelConflict(projectId,Number(payload?.currentVersion)||0);return;}}catch{} }
export async function hydrateModel(projectId:string|undefined,fallback:BuildingModel){if(!projectId)return loadModel(projectId,fallback);try{const response=await fetch(`/api/projects/${encodeURIComponent(projectId)}/model`,{cache:"no-store"});if(response.ok){const payload=await response.json();const remote=payload?.model?.model;if(validModel(remote)){const normalized={...remote,modelId:`bm-${projectId}-v1`,rooms:remote.rooms.map(r=>normalizeRoom(r,remote.plot))};try{localStorage.setItem(storageKey(projectId),JSON.stringify(normalized));}catch{}return normalized;}}
    const siteResponse=await fetch(`/api/projects/${encodeURIComponent(projectId)}/site`,{cache:"no-store"});
    if(siteResponse.ok){const sitePayload=await siteResponse.json();const site=sitePayload?.site;const width=Number(site?.plot_width_m);const depth=Number(site?.plot_depth_m);if(Number.isFinite(width)&&width>0&&Number.isFinite(depth)&&depth>0){const plot={width,depth};const seeded={...fallback,modelId:`bm-${projectId}-v1`,plot,rooms:fallback.rooms.map(r=>normalizeRoom(r,plot))};try{localStorage.setItem(storageKey(projectId),JSON.stringify(seeded));}catch{}return seeded;}}
  }catch{}return loadModel(projectId,fallback);}
export function commitModel(projectId:string|undefined,current:BuildingModel,id:string,patch:Partial<Pick<Room,"x"|"y"|"w"|"h">>){const next=applyModelChange(current,id,patch);saveModel(projectId,next);return next;}
