'use client';
import { useState } from 'react';

export default function NewProject() {
  const [lat,setLat]=useState(''); const [lon,setLon]=useState(''); const [width,setWidth]=useState(''); const [depth,setDepth]=useState('');
  const [result,setResult]=useState<any>(null); const [loading,setLoading]=useState(false);
  async function analyze(){ setLoading(true); setResult(null); try { const r=await fetch('/api/site-resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lat:Number(lat),lon:Number(lon),width:Number(width),depth:Number(depth)})}); setResult(await r.json()); } finally { setLoading(false); } }
  return <main className="workspace"><header><a href="/" className="brand">BUILD AI</a><span>Site Intelligence · v0.3</span></header><section className="panel"><div><p className="eyebrow">01 · SITE</p><h1>Resolve the site before designing the building.</h1><p className="muted">Enter coordinates and optional plot dimensions. Build Ai resolves the planning context first, then hands verified constraints to the design engine.</p></div><div className="grid"><label>Latitude<input value={lat} onChange={e=>setLat(e.target.value)} placeholder="28.6139" /></label><label>Longitude<input value={lon} onChange={e=>setLon(e.target.value)} placeholder="77.2090" /></label><label>Plot width (m)<input value={width} onChange={e=>setWidth(e.target.value)} placeholder="10" /></label><label>Plot depth (m)<input value={depth} onChange={e=>setDepth(e.target.value)} placeholder="20" /></label></div><button onClick={analyze} disabled={loading}>{loading?'Resolving…':'Analyze site'}</button>{result&&<div className="result"><div><span>Authority</span><strong>{result.jurisdiction?.authority}</strong></div><div><span>Confidence</span><strong>{result.jurisdiction?.confidence}</strong></div><div><span>Plot area</span><strong>{result.plot?`${result.plot.area_sqm} m²`:'Not supplied'}</strong></div><div className="wide"><span>Regulatory engine</span><strong>{result.regulatory_status}</strong></div></div>}</section></main>
}
